#-----------------------------
# # completion
#-----------------------------
[[plugins]]
repo        = 'Shougo/neocomplete.vim'
on_i        = 1
hook_source = '''
    runtime $PLUGIN_VIM/neocomplete.vim
'''

#-----------------------------
# # unite
#-----------------------------
[[plugins]]
repo        = 'Shougo/unite.vim'
on_cmd      = 'Unite'
hook_add    = '''
    nnoremap <silent> uf :<C-u>Unite<Space>file<CR>
    nnoremap <silent> ub :<C-u>Unite<Space>buffer<CR>
'''
